### PR TITLE
hook onConnection and onQuery

### PR DESCRIPTION
**Pull request by zhennann**
## [Feature Request]想给egg-mysql提交一个PR
[eggjs/egg#4003](https://github.com/eggjs/egg/issues/4003)

## egg-mysql 如何像sequelize一样打印执行的SQL日志?
[eggjs/egg#648](https://github.com/eggjs/egg/issues/648)

### CODE REVIEW

**Comment by zhennann** [comment]
@fengmk2  Could you spare some time for review？

**Comment by hyj1991** [comment]
CI 好像挂了

**Comment by zhennann** [comment]
The module istanbul use `async` syntax which is not valid in node 6

**Comment by zhennann** [comment]
Specify mocha to 6.x, because mocha 7.x has dropped node 6.x support

**Comment by fengmk2** [comment]
https://github.com/ali-sdk/ali-rds/pull/104

**Pull request closed without merging**
